############################################################################
# drivers/sensors/Makefile
#
# This Makefile is NOT used by the NuttX build system directly.
# NuttX picks up these sources via drivers/sensors/Make.defs, which is
# pulled in through nuttxspace/nuttx/drivers/platform/Make.defs when
# CONFIG_SPECIFIC_DRIVERS=y.
#
# This file exists as a stub for standalone tooling (linters, IDE indexers).
############################################################################
